name: Linux build and test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  linux_build_from_conda_forge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
        build_shared: [ON, OFF]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create build environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ./environment-dev.yml
          environment-name: build_env
          cache-environment: true
      - name: Install external dependencies
        run: micromamba install -n build_env -y -f ./environment-dev.yml
      - name: Build sparrow-ipc
        run: |
          cmake -B build/ -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DSPARROW_IPC_BUILD_SHARED=${{ matrix.build_shared }} \
            -DSPARROW_IPC_BUILD_TESTS=ON
          cmake --build build/ --parallel
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

  linux_build_fetch_from_source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
        build_shared: [ON, OFF]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create build environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ./environment-dev.yml
          environment-name: build_env
          cache-environment: true
      - name: Build sparrow-ipc
        run: |
          cmake -B build/ -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            -DSPARROW_IPC_BUILD_SHARED=${{ matrix.build_shared }} \
            -DFETCH_DEPENDENCIES_WITH_CMAKE=MISSING \
            -DSPARROW_IPC_BUILD_TESTS=ON
          cmake --build build/ --parallel
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
