name: Windows build and test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    # micromamba activation
    shell: cmd /C call {0}

jobs:
  windows_build_from_conda_forge:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
        build_shared: [ON, OFF]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ./environment-dev.yml
          environment-name: build_env
          cache-environment: true
          init-shell: cmd.exe

      - name: Configure using cmake
        run: |
          cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX% \
          -DCMAKE_PREFIX_PATH=%CONDA_PREFIX% \
          -DSPARROW_IPC_BUILD_SHARED=${{ matrix.build_shared }} \
          -DSPARROW_IPC_BUILD_TESTS=ON

      - name: Build sparrow-ipc
        working-directory: build
        run: cmake --build . --config ${{matrix.build_type}} --target sparrow-ipc

      - name: Build tests
        working-directory: build
        run: cmake --build . --config ${{matrix.config}} --target test_sparrow_ipc_lib

      - name: Run tests
        working-directory: build
        run: |
          cmake --build . --config ${{matrix.config}} --target run_tests


  windows_build_fetch_from_source:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
        build_shared: [ON, OFF]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure using cmake
        run: |
          cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DSPARROW_IPC_BUILD_SHARED=${{ matrix.build_shared }} \
          -DSPARROW_IPC_BUILD_TESTS=ON \
          -DFETCH_DEPENDENCIES_WITH_CMAKE=MISSING

      - name: Build sparrow-ipc
        working-directory: build
        run: cmake --build . --config ${{matrix.build_type}} --target sparrow-ipc

      - name: Build tests
        working-directory: build
        run: cmake --build . --config ${{matrix.config}} --target test_sparrow_ipc_lib

      - name: Run tests
        working-directory: build
        run: cmake --build . --config ${{matrix.config}} --target run_tests_with_junit_report
